version: '3.8'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn core.wsgi -b 0.0.0.0:8000    
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=_=d0=yr$$%g0e5k%h40bp&eh5b71kb@qfgdl_ydqxv25rw!a0p*
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: